# Generated by Django 4.2.25 on 2025-10-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('apartment', 'شقة'), ('office', 'مكتب تجاري'), ('shop', 'محل تجاري'), ('warehouse', 'مستودع للتخزين')], max_length=30, verbose_name='نوع الوحدة'),
        ),
    ]
