# Generated by Django 4.2.25 on 2025-10-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_update_unit_type_choices_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='tenant_type',
            field=models.CharField(choices=[('sole_proprietorship', 'شركة الشخص الواحد'), ('limited_liability', 'الشركة ذات المسؤولية المحدودة'), ('joint_stock', 'الشركة المساهمة'), ('general_partnership', 'شركة التضامن'), ('limited_partnership', 'شركة التوصية البسيطة'), ('holding_company', 'الشركة القابضة'), ('representative_office', 'مكتب تمثيل تجاري'), ('foreign_branch', 'فرع شركة أجنبية')], max_length=50, verbose_name='نوع المستأجر'),
        ),
    ]
