# Generated by Django 4.2.25 on 2025-10-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_update_tenant_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name_english',
            field=models.CharField(blank=True, help_text='ترجمة تلقائية للاسم الأول', max_length=150, null=True, verbose_name='الاسم الأول بالإنجليزية'),
        ),
    ]
