# Generated by Django 4.2.25 on 2025-10-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_add_english_name_translation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lease',
            options={'permissions': [('can_view_financial_reports', 'Can view financial reports'), ('can_manage_leases', 'Can manage leases'), ('can_manage_notices', 'Can manage notices'), ('can_access_settings', 'Can access settings')], 'verbose_name': 'عقد إيجار', 'verbose_name_plural': 'عقود الإيجار'},
        ),
    ]
