# Generated by Django 4.2.25 on 2025-10-21 19:16

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Custom permissions
    can_view_financial_reports = Permission.objects.get(codename='can_view_financial_reports')
    can_manage_leases = Permission.objects.get(codename='can_manage_leases')
    can_manage_notices = Permission.objects.get(codename='can_manage_notices')
    can_access_settings = Permission.objects.get(codename='can_access_settings')

    # Default permissions
    add_lease = Permission.objects.get(codename='add_lease')
    change_lease = Permission.objects.get(codename='change_lease')
    delete_lease = Permission.objects.get(codename='delete_lease')
    view_lease = Permission.objects.get(codename='view_lease')

    add_payment = Permission.objects.get(codename='add_payment')
    view_payment = Permission.objects.get(codename='view_payment')

    add_tenant = Permission.objects.get(codename='add_tenant')
    change_tenant = Permission.objects.get(codename='change_tenant')
    view_tenant = Permission.objects.get(codename='view_tenant')

    # Create Groups
    admin_group, _ = Group.objects.get_or_create(name='System Admin')
    accountant_group, _ = Group.objects.get_or_create(name='Accountant')
    data_entry_group, _ = Group.objects.get_or_create(name='Data Entry')

    # Assign permissions
    admin_group.permissions.set(Permission.objects.all())

    accountant_permissions = [
        can_view_financial_reports,
        view_lease,
        add_payment,
        view_payment,
    ]
    accountant_group.permissions.set(accountant_permissions)

    data_entry_permissions = [
        can_manage_leases,
        add_lease,
        change_lease,
        view_lease,
        add_tenant,
        change_tenant,
        view_tenant,
    ]
    data_entry_group.permissions.set(data_entry_permissions)

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_lease_options'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]


