# Generated by Django 4.2.25 on 2025-10-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access_settings',
            field=models.BooleanField(default=False, help_text='تعديل إعدادات النظام', verbose_name='الوصول إلى الإعدادات'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_export_reports',
            field=models.BooleanField(default=False, help_text='تصدير التقارير إلى PDF/Excel', verbose_name='تصدير التقارير'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_buildings',
            field=models.BooleanField(default=False, help_text='إضافة، تعديل، حذف المباني', verbose_name='إدارة المباني'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_expenses',
            field=models.BooleanField(default=False, help_text='إضافة، تعديل، حذف المصروفات', verbose_name='إدارة المصروفات'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_invoices',
            field=models.BooleanField(default=False, help_text='إنشاء، تعديل، حذف الفواتير', verbose_name='إدارة الفواتير'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_leases',
            field=models.BooleanField(default=False, help_text='إضافة، تعديل، حذف، تجديد، إلغاء العقود', verbose_name='إدارة العقود'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_notices',
            field=models.BooleanField(default=False, help_text='إنشاء، تعديل، إرسال الإنذارات', verbose_name='إدارة الإنذارات'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_payments',
            field=models.BooleanField(default=False, help_text='إضافة، تعديل، حذف الدفعات', verbose_name='إدارة الدفعات'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_tenants',
            field=models.BooleanField(default=False, help_text='إضافة، تعديل، حذف المستأجرين', verbose_name='إدارة المستأجرين'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_units',
            field=models.BooleanField(default=False, help_text='إضافة، تعديل، حذف الوحدات', verbose_name='إدارة الوحدات'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_users',
            field=models.BooleanField(default=False, help_text='إضافة، تعديل، حذف المستخدمين وصلاحياتهم', verbose_name='إدارة المستخدمين'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_buildings',
            field=models.BooleanField(default=True, verbose_name='عرض المباني'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_expenses',
            field=models.BooleanField(default=False, verbose_name='عرض المصروفات'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_invoices',
            field=models.BooleanField(default=False, verbose_name='عرض الفواتير'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_leases',
            field=models.BooleanField(default=True, verbose_name='عرض العقود'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_notices',
            field=models.BooleanField(default=False, verbose_name='عرض الإنذارات'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_payments',
            field=models.BooleanField(default=False, verbose_name='عرض الدفعات'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_reports',
            field=models.BooleanField(default=False, verbose_name='عرض التقارير'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_tenants',
            field=models.BooleanField(default=True, verbose_name='عرض المستأجرين'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_units',
            field=models.BooleanField(default=True, verbose_name='عرض الوحدات'),
        ),
    ]
