# Generated by Django 4.2.25 on 2025-10-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_add_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_view_dashboard',
            field=models.BooleanField(default=True, help_text='الوصول إلى لوحة التحكم الرئيسية', verbose_name='عرض لوحة التحكم'),
        ),
    ]
