# Generated by Django 4.2.25 on 2025-10-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_add_can_view_dashboard_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_view_dashboard_calendar',
            field=models.BooleanField(default=True, help_text='تقويم تجديد العقود', verbose_name='عرض تقويم التجديد'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_dashboard_charts',
            field=models.BooleanField(default=True, help_text='اتجاه الإيرادات، إشغال الوحدات', verbose_name='عرض المخططات البيانية'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_dashboard_financial',
            field=models.BooleanField(default=False, help_text='الدخل المتوقع، المصاريف، صافي الدخل', verbose_name='عرض البيانات المالية'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_dashboard_stats',
            field=models.BooleanField(default=True, help_text='بطاقة العقود النشطة', verbose_name='عرض إحصائيات العقود'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_dashboard_transactions',
            field=models.BooleanField(default=False, help_text='آخر الدفعات والمصاريف', verbose_name='عرض الحركات المالية'),
        ),
    ]
