# Generated by Django 4.2.25 on 2025-10-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_add_dashboard_detailed_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='cancellation_details',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل إضافية عن سبب الإلغاء'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('contract_term_ended', 'انتهاء المدة المحددة في العقد'), ('non_payment', 'عدم دفع الإيجار لأكثر من شهرين متتاليين'), ('tenant_violation', 'مخالفة شروط العقد من قبل المستأجر'), ('owner_reclaim', 'رغبة المالك في استرداد العقار'), ('tenant_request', 'رغبة المستأجر في إنهاء العقد'), ('other', 'أسباب أخرى')], max_length=200, null=True, verbose_name='سبب الإلغاء'),
        ),
    ]
