# Generated by Django 4.2.25 on 2025-10-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_add_cancellation_details_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='cancellation_reason',
            field=models.CharField(blank=True, help_text='يمكنك اختيار حتى 3 أسباب، مفصولة بفواصل', max_length=500, null=True, verbose_name='أسباب الإلغاء'),
        ),
    ]
