# Generated by Django 4.2.25 on 2025-10-22 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0011_alter_lease_cancellation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('category', models.CharField(choices=[('payment', 'دفعة'), ('lease', 'عقد'), ('maintenance', 'صيانة'), ('overdue', 'تأخير سداد'), ('reminder', 'تذكير'), ('system', 'نظام'), ('security', 'أمان'), ('general', 'عام')], default='general', max_length=20, verbose_name='التصنيف')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=10, verbose_name='الأولوية')),
                ('channels', models.JSONField(default=list, help_text='القنوات التي تم إرسال الإشعار عبرها', verbose_name='القنوات')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('action_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='رابط الإجراء')),
                ('action_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='نص الإجراء')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القراءة')),
                ('sent_via_email', models.BooleanField(default=False, verbose_name='تم الإرسال عبر البريد')),
                ('sent_via_sms', models.BooleanField(default=False, verbose_name='تم الإرسال عبر SMS')),
                ('sent_via_whatsapp', models.BooleanField(default=False, verbose_name='تم الإرسال عبر واتساب')),
                ('sent_via_push', models.BooleanField(default=False, verbose_name='تم الإرسال عبر Push')),
                ('delivery_log', models.JSONField(blank=True, default=dict, verbose_name='سجل التسليم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد الإرسال')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار محسّن',
                'verbose_name_plural': 'الإشعارات المحسّنة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnhancedNotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القالب')),
                ('category', models.CharField(choices=[('payment', 'دفعة'), ('lease', 'عقد'), ('maintenance', 'صيانة'), ('overdue', 'تأخير سداد'), ('reminder', 'تذكير'), ('system', 'نظام'), ('security', 'أمان'), ('general', 'عام')], default='general', max_length=20, verbose_name='التصنيف')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('body_text', models.TextField(verbose_name='المحتوى النصي')),
                ('body_html', models.TextField(blank=True, null=True, verbose_name='المحتوى HTML')),
                ('channels', models.JSONField(default=list, help_text='قائمة القنوات: in_app, email, sms, whatsapp, push', verbose_name='القنوات المفعلة')),
                ('variables', models.JSONField(default=dict, help_text='المتغيرات المتاحة في القالب', verbose_name='المتغيرات')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قالب إشعار محسّن',
                'verbose_name_plural': 'قوالب الإشعارات المحسّنة',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='device_token',
            field=models.CharField(blank=True, help_text='Firebase device token للإشعارات الفورية', max_length=255, null=True, verbose_name='رمز الجهاز'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='رقم واتساب لاستقبال الإشعارات', max_length=20, null=True, verbose_name='رقم واتساب'),
        ),
        migrations.CreateModel(
            name='EnhancedNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_in_app', models.BooleanField(default=True, verbose_name='تفعيل الإشعارات الداخلية')),
                ('enable_email', models.BooleanField(default=True, verbose_name='تفعيل البريد الإلكتروني')),
                ('enable_sms', models.BooleanField(default=False, verbose_name='تفعيل الرسائل النصية')),
                ('enable_whatsapp', models.BooleanField(default=False, verbose_name='تفعيل واتساب')),
                ('enable_push', models.BooleanField(default=True, verbose_name='تفعيل الإشعارات الفورية')),
                ('categories', models.JSONField(default=dict, help_text='تفعيل/تعطيل كل تصنيف لكل قناة', verbose_name='التصنيفات المفعلة')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='بداية وقت الهدوء')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='نهاية وقت الهدوء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تفضيلات الإشعارات المحسّنة',
                'verbose_name_plural': 'تفضيلات الإشعارات المحسّنة',
            },
        ),
        migrations.CreateModel(
            name='EnhancedNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'داخل التطبيق'), ('email', 'البريد الإلكتروني'), ('sms', 'رسالة نصية'), ('whatsapp', 'واتساب'), ('push', 'إشعار فوري')], max_length=20, verbose_name='القناة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('sent', 'تم الإرسال'), ('delivered', 'تم التسليم'), ('failed', 'فشل'), ('bounced', 'مرتد')], default='pending', max_length=20, verbose_name='الحالة')),
                ('recipient', models.CharField(max_length=200, verbose_name='المستلم')),
                ('provider', models.CharField(blank=True, max_length=50, null=True, verbose_name='مزود الخدمة')),
                ('provider_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='معرف المزود')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات الاستجابة')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='التكلفة')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التسليم')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.enhancednotification', verbose_name='الإشعار')),
            ],
            options={
                'verbose_name': 'سجل إشعار محسّن',
                'verbose_name_plural': 'سجلات الإشعارات المحسّنة',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='enhancednotification',
            index=models.Index(fields=['user', '-created_at'], name='dashboard_e_user_id_04fd01_idx'),
        ),
        migrations.AddIndex(
            model_name='enhancednotification',
            index=models.Index(fields=['user', 'is_read'], name='dashboard_e_user_id_b07f37_idx'),
        ),
        migrations.AddIndex(
            model_name='enhancednotification',
            index=models.Index(fields=['category', '-created_at'], name='dashboard_e_categor_81ba68_idx'),
        ),
    ]
