# Generated by Django 4.2.25 on 2025-10-22 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0012_add_enhanced_notification_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التقرير')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('report_type', models.CharField(choices=[('profitability', 'تقرير الربحية'), ('cash_flow', 'تقرير التدفق النقدي'), ('occupancy', 'تقرير معدل الإشغال'), ('overdue_tenants', 'تقرير المستأجرين المتأخرين'), ('revenue', 'تقرير الإيرادات'), ('expenses', 'تقرير المصروفات'), ('lease_expiry', 'تقرير انتهاء العقود'), ('tenant_rating', 'تقرير تقييم المستأجرين'), ('unit_performance', 'تقرير أداء الوحدات'), ('custom', 'تقرير مخصص')], max_length=50, verbose_name='نوع التقرير')),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي'), ('custom', 'مخصص')], default='monthly', max_length=20, verbose_name='التكرار')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], default='pdf', max_length=20, verbose_name='الصيغة')),
                ('recipient_emails', models.TextField(blank=True, help_text='عناوين بريد إلكتروني إضافية مفصولة بفواصل', null=True, verbose_name='بريد إلكتروني إضافي')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='فلاتر التقرير (مباني، وحدات، تواريخ، إلخ)', verbose_name='الفلاتر')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='التشغيل التالي')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='آخر تشغيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_reports', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('recipients', models.ManyToManyField(help_text='المستخدمون الذين سيستلمون التقرير', related_name='scheduled_reports', to=settings.AUTH_USER_MODEL, verbose_name='المستلمون')),
            ],
            options={
                'verbose_name': 'تقرير مجدول',
                'verbose_name_plural': 'التقارير المجدولة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('period_type', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي')], max_length=20, verbose_name='نوع الفترة')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الإيرادات')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المصروفات')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='صافي الربح')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='هامش الربح %')),
                ('total_units', models.IntegerField(default=0, verbose_name='إجمالي الوحدات')),
                ('occupied_units', models.IntegerField(default=0, verbose_name='الوحدات المشغولة')),
                ('occupancy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='معدل الإشغال %')),
                ('active_leases', models.IntegerField(default=0, verbose_name='العقود النشطة')),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبالغ المتأخرة')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحساب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'تحليلات التقرير',
                'verbose_name_plural': 'تحليلات التقارير',
                'ordering': ['-period_end'],
                'unique_together': {('period_start', 'period_end', 'period_type')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('profitability', 'تقرير الربحية'), ('cash_flow', 'تقرير التدفق النقدي'), ('occupancy', 'تقرير معدل الإشغال'), ('overdue_tenants', 'تقرير المستأجرين المتأخرين'), ('revenue', 'تقرير الإيرادات'), ('expenses', 'تقرير المصروفات'), ('lease_expiry', 'تقرير انتهاء العقود'), ('tenant_rating', 'تقرير تقييم المستأجرين'), ('unit_performance', 'تقرير أداء الوحدات'), ('custom', 'تقرير مخصص')], max_length=50, verbose_name='نوع التقرير')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('data', models.JSONField(default=dict, help_text='بيانات التقرير المُنشأ', verbose_name='البيانات')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='الملف')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], max_length=20, verbose_name='الصيغة')),
                ('status', models.CharField(choices=[('generating', 'قيد الإنشاء'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('sent', 'تم الإرسال')], default='generating', max_length=20, verbose_name='الحالة')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='حجم الملف')),
                ('download_count', models.IntegerField(default=0, verbose_name='عدد التنزيلات')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('scheduled_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='dashboard.scheduledreport', verbose_name='التقرير المجدول')),
            ],
            options={
                'verbose_name': 'تقرير مُنشأ',
                'verbose_name_plural': 'التقارير المُنشأة',
                'ordering': ['-generated_at'],
            },
        ),
    ]
