# Generated by Django 5.2.7 on 2025-10-08 18:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_otp_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المالك')),
                ('owner_type', models.CharField(choices=[('individual', 'فرد'), ('company', 'شركة'), ('government', 'حكومي')], default='individual', max_length=20, verbose_name='نوع المالك')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهوية/السجل التجاري')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الحساب البنكي')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم البنك')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مالك مبنى',
                'verbose_name_plural': 'مالكو المباني',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RealEstateOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المكتب العقاري')),
                ('license_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الترخيص')),
                ('contact_person', models.CharField(max_length=150, verbose_name='الشخص المسؤول')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='النسبة المئوية من الإيجار الشهري', max_digits=5, verbose_name='نسبة العمولة الافتراضية (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مكتب عقاري',
                'verbose_name_plural': 'المكاتب العقارية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommissionAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الاتفاقية')),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='النسبة المئوية من الإيجار الشهري', max_digits=5, verbose_name='نسبة العمولة (%)')),
                ('start_date', models.DateField(verbose_name='تاريخ بدء الاتفاقية')),
                ('end_date', models.DateField(verbose_name='تاريخ انتهاء الاتفاقية')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('cancelled', 'ملغي')], default='active', max_length=20, verbose_name='حالة الاتفاقية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.building', verbose_name='المبنى')),
                ('building_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.buildingowner', verbose_name='مالك المبنى')),
                ('real_estate_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.realestateoffice', verbose_name='المكتب العقاري')),
            ],
            options={
                'verbose_name': 'اتفاقية عمولة',
                'verbose_name_plural': 'اتفاقيات العمولة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الاستلام')),
                ('amount_collected', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المستلم')),
                ('collection_method', models.CharField(choices=[('cash', 'نقداً'), ('check', 'شيك'), ('bank_transfer', 'تحويل بنكي'), ('other', 'أخرى')], max_length=20, verbose_name='طريقة الاستلام')),
                ('status', models.CharField(choices=[('collected', 'تم الاستلام'), ('pending', 'في الانتظار'), ('overdue', 'متأخر')], default='collected', max_length=20, verbose_name='حالة الاستلام')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.lease', verbose_name='العقد')),
                ('real_estate_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.realestateoffice', verbose_name='المكتب العقاري')),
            ],
            options={
                'verbose_name': 'استلام إيجار',
                'verbose_name_plural': 'استلام الإيجارات',
                'ordering': ['-collection_date'],
            },
        ),
        migrations.CreateModel(
            name='CommissionDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_share', models.DecimalField(decimal_places=2, help_text='المبلغ المستحق لمالك المبنى', max_digits=10, verbose_name='حصة المالك')),
                ('office_commission', models.DecimalField(decimal_places=2, help_text='عمولة المكتب العقاري', max_digits=10, verbose_name='عمولة المكتب')),
                ('distribution_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوزيع')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('distributed', 'تم التوزيع'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة التوزيع')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'نقداً'), ('check', 'شيك'), ('bank_transfer', 'تحويل بنكي'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='طريقة الدفع')),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='مرجع الدفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('building_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.buildingowner', verbose_name='مالك المبنى')),
                ('commission_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.commissionagreement', verbose_name='اتفاقية العمولة')),
                ('rent_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.rentcollection', verbose_name='استلام الإيجار')),
            ],
            options={
                'verbose_name': 'توزيع عمولة',
                'verbose_name_plural': 'توزيع العمولات',
                'ordering': ['-created_at'],
            },
        ),
    ]
