# Generated by Django 5.2.7 on 2025-10-08 18:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_buildingowner_realestateoffice_commissionagreement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الاستلام')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ التأمين')),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً'), ('check', 'شيك'), ('bank_transfer', 'تحويل بنكي'), ('other', 'أخرى')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('check_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الشيك')),
                ('check_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الشيك')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم البنك')),
                ('check_status', models.CharField(blank=True, choices=[('pending', 'معلق - في الانتظار'), ('cashed', 'تم الصرف'), ('returned', 'مرتجع')], default='pending', max_length=20, null=True, verbose_name='حالة الشيك')),
                ('return_reason', models.TextField(blank=True, null=True, verbose_name='سبب إرجاع الشيك')),
                ('status', models.CharField(choices=[('held', 'محجوز'), ('refunded', 'تم إرجاعه'), ('applied', 'مستخدم')], default='held', max_length=20, verbose_name='حالة التأمين')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_deposits', to='dashboard.lease', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'تأمين',
                'verbose_name_plural': 'التأمينات',
                'ordering': ['-received_date'],
            },
        ),
    ]
