# Generated by Django 4.2.25 on 2025-10-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_securitydeposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('expiring_soon', 'قريب الانتهاء'), ('expired', 'منتهي'), ('renewed', 'تم تجديد'), ('cancelled', 'ملغي')], default='active', editable=False, max_length=20, verbose_name='حالة العقد'),
        ),
    ]
