# Generated by Django 4.2.25 on 2025-10-19 06:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_lease_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القالب')),
                ('template_type', models.CharField(choices=[('overdue_payment', 'إنذار عدم سداد'), ('contract_termination', 'إنذار فسخ عقد'), ('eviction_notice', 'إنذار إخلاء'), ('lease_renewal', 'تذكير تجديد عقد'), ('maintenance_notice', 'إشعار صيانة')], max_length=30, verbose_name='نوع القالب')),
                ('subject', models.CharField(max_length=300, verbose_name='الموضوع')),
                ('content', models.TextField(help_text='استخدم المتغيرات مثل {tenant_name}, {unit_number}, {amount}, {due_date}', verbose_name='المحتوى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('legal_compliance_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الامتثال القانوني')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قالب إنذار',
                'verbose_name_plural': 'قوالب الإنذارات',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOverdueNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الإنذار')),
                ('overdue_month', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='الشهر المتأخر')),
                ('overdue_year', models.IntegerField(default=2025, verbose_name='السنة المتأخرة')),
                ('overdue_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المتأخر')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق الأصلي')),
                ('legal_deadline', models.DateField(verbose_name='الموعد النهائي القانوني')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'تم الإرسال'), ('acknowledged', 'تم الاستلام'), ('resolved', 'تم الحل'), ('escalated', 'تم التصعيد')], default='draft', max_length=20, verbose_name='حالة الإنذار')),
                ('potential_legal_action', models.CharField(choices=[('none', 'لا يوجد'), ('contract_termination', 'فسخ العقد'), ('eviction', 'الإخلاء'), ('legal_proceedings', 'إجراءات قانونية')], default='contract_termination', max_length=30, verbose_name='الإجراء القانوني المحتمل')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('acknowledged_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستلام')),
                ('resolved_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('delivery_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='طريقة التسليم')),
                ('recipient_signature', models.CharField(blank=True, max_length=100, null=True, verbose_name='توقيع المستلم')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overdue_notices', to='dashboard.lease', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'إنذار عدم سداد',
                'verbose_name_plural': 'إنذارات عدم السداد',
                'ordering': ['-notice_date'],
                'unique_together': {('lease', 'overdue_month', 'overdue_year')},
            },
        ),
    ]
