# Generated by Django 4.2.25 on 2025-10-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_add_overdue_notice_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('apartment', 'شقة'), ('residential_unit', 'وحدة سكنية'), ('office', 'مكتب'), ('workspace', 'مساحة عمل مكتبية'), ('shop', 'محل'), ('commercial_shop', 'محل تجاري'), ('warehouse', 'مستودع'), ('showroom', 'معرض')], max_length=30, verbose_name='نوع الوحدة'),
        ),
    ]
