# Generated by Django 4.2.25 on 2025-10-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_update_unit_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='tenant_type',
            field=models.CharField(choices=[('individual', 'فرد'), ('natural_person', 'شخص طبيعي'), ('company', 'شركة'), ('legal_entity', 'كيان قانوني')], max_length=25, verbose_name='نوع المستأجر'),
        ),
    ]
