# Generated by Django 4.2.25 on 2025-10-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_update_tenant_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='tenant_type',
            field=models.CharField(choices=[('individual', 'فرد'), ('natural_person', 'شخص طبيعي'), ('company', 'شركة'), ('legal_entity', 'كيان قانوني'), ('corporation', 'مؤسسة'), ('partnership', 'شراكة')], max_length=30, verbose_name='نوع المستأجر'),
        ),
    ]
