# Generated by Django 4.2.25 on 2025-10-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_update_tenant_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.CharField(blank=True, help_text='رقم السجل التجاري أو الهوية الضريبية', max_length=50, null=True, verbose_name='هوية الشركة'),
        ),
    ]
