# Generated by Django 4.2.25 on 2025-10-21 11:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_add_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseRenewalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التذكير')),
                ('days_before_expiry', models.IntegerField(default=30, verbose_name='عدد الأيام قبل الانتهاء')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('sent', 'تم الإرسال'), ('acknowledged', 'تم الاستلام'), ('responded', 'تم الرد'), ('expired', 'منتهي الصلاحية')], default='pending', max_length=20, verbose_name='حالة التذكير')),
                ('response', models.CharField(blank=True, choices=[('no_response', 'لا رد'), ('interested', 'مهتم بالتجديد'), ('not_interested', 'غير مهتم بالتجديد'), ('negotiating', 'قيد التفاوض')], default='no_response', max_length=20, null=True, verbose_name='رد المستأجر')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرد')),
                ('response_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الرد')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('delivery_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='طريقة التسليم')),
                ('recipient_signature', models.CharField(blank=True, max_length=100, null=True, verbose_name='توقيع المستلم')),
                ('proposed_renewal_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التجديد المقترح')),
                ('proposed_monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='إيجار شهري مقترح')),
                ('proposed_terms', models.TextField(blank=True, null=True, verbose_name='شروط التجديد المقترحة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_reminders', to='dashboard.lease', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'تذكير تجديد عقد',
                'verbose_name_plural': 'تذكيرات تجديد العقود',
                'ordering': ['-reminder_date'],
                'unique_together': {('lease', 'reminder_date')},
            },
        ),
    ]
